### ISSUE TITLE
Make prettify of ini configurable

### ISSUE THREAD

**Issue by noxan** [sapegin/mrm-core#10]
I was curious if there is a chance of making the prettify step within the save function of ini files configurable? 

This is how I would imagine the api.
```
ini('file.ini').save({ prettify: false });
```

I would be willing to implement, just asking ahead not to waste time.

PS. Thanks so much for this awesome project :)

**Comment by sapegin** [comment]
No, but I guess we can infer the original style, the same way we infer indentation in JSON.

**Comment by noxan** [comment]
What do you think of how the logic for this detection work. Match the first line and see if it is separated by `·=·` or by `=`? Fallback to default if detection fails?
(Highlighted space with `·`, otherwise you don't see a difference)
Furthermore this way there would be no way of creating new files with the `=` version.

Let me know what suits you best, I need the last mentioned one for a specific use case and would rather contribute upstream instead of creating individual solutions. But no hard feelings if it does not match.

**Comment by sapegin** [comment]
You’re right about new files :-/

Then I guess the best we can do is an option. Default value would be inferred from an original file if we have one, or adding whitespace if we’re creating a new file.

> Match the first line and see if it is separated by ·=· or by =? Fallback to default if detection fails?

Yep, the first line which is not a comment.

**Comment by TrySound** [comment]
I tried to use for flow config which do not accepts spaces around `=`. By default it's empty, nothing to infer.

**Comment by sapegin** [comment]
@TrySound That’s why

> Then I guess the best we can do is an option
