### ISSUE TITLE
YML files are changed with updated formatting

### ISSUE THREAD

**Issue by ivn-cote** [sapegin/mrm-core#16]
When I tried the simple script with updating `.travis.yml` file, I've got many formatting changes which are pretty annoying.

So the script could be like this
```
const { yaml } = require('mrm-core');

function task() {
  yaml('.travis.yml')
    .merge({ 'before_script': [
      './cc-test-reporter before-build'
    ]})
    .save();
};

task.description = 'Update CodeClimate usage on Travis CI';
module.exports = task;
```

And a result I have:
1) removed spaces for key-value pairs, e.g. `provider: <5 spaces> s3` --> `provider:<1 space> s3`
2) appended quotes. e.g. `on:` --> `'on':`
3) removed comments, e.g. `# also update .node_version` --> ` `

Is it possible to quickly update the YML parser at the project to mitigate this side-effects?
Thanks!

**Comment by sapegin** [comment]
We we'll never keep the original formatting if it was done manually, but better parser of course may help to make output better (keep comments for examples — [yaml](https://github.com/eemeli/yaml) could be a good option).

Feel free to send a pull request.

**Comment by sapegin** [comment]
I’m closing this for now. Feel free to submit a pull request if you need this.
