### ISSUE TITLE
Run all tasks flag

### ISSUE THREAD

**Issue by shellscape** [sapegin/mrm-core#18]
Hey hey. Would love to have a flag added that would run all tasks available. Perhaps `--all`?

**Comment by sapegin** [comment]
What’s your use case for that? You can create an alias with all tasks that you _actually_ want to run.

**Comment by shellscape** [comment]
The use case would be for something along the lines of `webpack-defaults`. Now, `webpack-defaults` (you know this since you wrote it, only restating for folks who might happen across this) uses `mrm-core` directly and the tasks are executed via a Node script rather than run through `mrm` proper. For another project, we're using `mrm` proper for a similar result, and each time `mrm` is run we want all tasks to be run, as they all have to be applied to the target on each run of the tool.

The alias didn't stand out to me, and I'm more than happy to configure that. Thanks for pointing that out. That should get me by. It would only be marginally easier to add another flag to run them all, so I'm good if you defer to the alias for this and would like to close this issue.
