### ISSUE TITLE
The check for pre and post scripts skips prePublishOnly

### ISSUE THREAD

**Issue by thetutlage** [sapegin/mrm-core#19]
The code on this [line](https://github.com/sapegin/mrm-core/blob/master/src/files/packageJson.js#L32) checks for the `base script` to exist, when creating `pre` and `post` scripts. 

However, scripts like `prePublishOnly` can exists, without `publishOnly`. 

Do you think we should maintain a list of whitelisted scripts or remove the check for base script to exist?

**Comment by sapegin** [comment]
This check is for better ordering, so, for example, `posttest` will be right after `test`. It doesn't prevent you from having only `pre` or `post` scripts. Do you have any issues with the current behavior?

**Comment by thetutlage** [comment]
Ahh, my bad.

The issue seems to be somewhere else and I though that this line is causing the issue.

I tested with following code and works fine. Sorry for opening a redundant issue.

```js
const { packageJson } = require('mrm-core')

const pkg = packageJson()
pkg.appendScript('prepublishOnly', 'pkg-ok').save()
```
