### ISSUE TITLE
Make install @latest optionnal

### ISSUE THREAD

**Issue by npirotte** [sapegin/mrm-core#20]
Despite the install method is very handy, I found the version management a bit too restrictive.
It's nice to install latest, but it would be really nice to be able to specify a range to be able to install specific version / version range into a project.

Currently that "latest only" makes ht feature unusable for my use case and I ll have to rewrite this myself...

**Comment by sapegin** [comment]
Feel free to send a pull request to fix that.

**Comment by npirotte** [comment]
Thanks, I will do !

**Comment by sapegin** [comment]
I have no ideas on the possible API, but it will be likely a breaking change — don't worry about that if the API is good ;-)

**Comment by npirotte** [comment]
It depends if you want to maintain backward compatibility or not.

That should be be possible.

But for api clarity maybe it's better `install({ foo: "x.y.y"})` to behave like `npm install foo@x.y.z`

Up to you :)

I ll make a proposal

**Comment by sapegin** [comment]
I'd like to preserve the default behavior, so `install(['eslint'])` will install the latest version. But I'm fine changing explicit version to match npm (if that's what you're proposing).

**Comment by npirotte** [comment]
yes, that's the idea.

`install(['eslint'])`=> `npm install eslint@latest`

And with explicit version latest in replaced by the version.

**Comment by sapegin** [comment]
That looks cool! How about defining a min version, like it's possible now?

**Comment by npirotte** [comment]
I can try something with `semver.satisfies`

For example with `^1.1.2`

```
semver.satisfies("1.1.1", "^1.1.2") => false
semver.satisfies("1.2.0", "^1.1.2") => true
```

in that case semver range defines the min version

The nice thing is that this would also allow to decrease a version.

**Comment by sapegin** [comment]
That looks great! 🦄
