### ISSUE TITLE
Add delete() method to all file types

### ISSUE THREAD

**Issue by sapegin** [sapegin/mrm-core#24]
```js
json('.eslintrc').delete()
```

* Should remove file if it exists.
* Should do nothing if file doesn't exist.

**Comment by aleung** [comment]
Is it a duplicated with `deleteFiles`?

**Comment by sapegin** [comment]
Not exactly, it's more of a shortcut for `deleteFiles`:

https://github.com/sapegin/mrm-tasks/blob/d02fc8cc33c7258c675fdb9006bbd8dec48ba782/packages/mrm-task-eslint/index.js#L27-L30
