### ISSUE TITLE
Add `delete` for file API

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm-core#3]
It would be more complete if we could also delete files in tasks.

**Comment by sapegin** [comment]
Would you mind sending a PR? ;-)

**Comment by okonet** [comment]
I'd love to but currently I'm very busy :(

**Comment by sapegin** [comment]
Me too ;-( Let’s mark this as an “easy task” then.

I propose a simple wrapper around [del.sync](https://github.com/sindresorhus/del) with an API like this:

```js
function delete(patterns)
```

Code would be similar to `makeDirs ` function:

https://github.com/sapegin/mrm-core/blob/2b72088653cb3aca82ab3077f1984c01cd003280/src/fs.js#L34-L46
