### ISSUE TITLE
mrm/src/index.js throws "module is not a function" error

### ISSUE THREAD

**Issue by ghost** [sapegin/mrm-core#41]
With the directory structure...

```
.mrm
├── config.json
├── editorconfig
│   └── index.js
├── package.json
└── yarn.lock
```
... and `editorconfig/index.js` consisting of (the example from this repo):

```
const { ini } = require('mrm-core')
ini('.editorconfig', 'editorconfig.org')
  .set('_global', { root: true })
  .set('*', {
    indent_style: 'tab',
    end_of_line: 'lf',
  })
  .save()
```

I get the `.editorconfig` I would expect as output—*but*, with the following error:

```
👻 ➜  .mrm git:(master) ✗ mrm editorconfig
Running editorconfig...
Create .editorconfig
/Users/me/.config/yarn/global/node_modules/mrm/bin/mrm.js:36
                throw err;
                ^

TypeError: module is not a function
    at /Users/me/.config/yarn/global/node_modules/mrm/src/index.js:136:19
    at new Promise (<anonymous>)
    at runTask (/Users/me/.config/yarn/global/node_modules/mrm/src/index.js:121:9)
    at run (/Users/me/.config/yarn/global/node_modules/mrm/src/index.js:81:9)
    at /Users/me/.config/yarn/global/node_modules/mrm/src/index.js:71:12
    at /Users/me/.config/yarn/global/node_modules/mrm/src/index.js:55:30
```

**Comment by ghost** [comment]
I see, I needed to at least export a module like so:

```
const { ini } = require('mrm-core')

function task() {
  ini('.editorconfig', 'editorconfig.org')
    .set('_global', { root: true })
    .set('*', {
      charset: 'utf-8',
      end_of_line: 'lf',
      indent_size: 2,
      indent_style: 'space',
      insert_final_newline: true,
      tab_width: 2,
      trim_trailing_whitespace: true,
    })
    .set('*.js', {
      quote_type: 'single',
    })
    .save()
}

task.description = 'Adds EditorConfig'
module.exports = task
```

I'll leave this open, as I don't know if that's the intended behavior or if `mrm/src/index.js` is supposed to check before calling `module()`. If not, maybe the API examples should be updated?

**Comment by sapegin** [comment]
Yeah, you need to export a module from a task. I think we can improve the error message though.

Where did you find this example?

**Comment by ghost** [comment]
https://github.com/sapegin/mrm-core#ini

**Comment by sapegin** [comment]
These are API examples, not complete task source.

**Comment by ghost** [comment]
I'm starting to piece that together, yes. The docs, being spread among multiple repos, all with circular references—it's a bit disorienting, trying to see the scope of it. That's just my experience however. Feel free to close this.🙂

**Comment by sapegin** [comment]
Yeah, it's not ideal now, so feel free to improve this 👾
