### ISSUE TITLE
ini: fail to set key into global section

### ISSUE THREAD

**Issue by aleung** [sapegin/mrm-core#5]
The file generated by example of `ini` misses the line `root = true`. This line is never generated by `editorconfig` neither.

```
const { ini } = require('mrm-core');
ini('.editorconfig', 'editorconfig.org')
  .set('root', true)
  .set('*', {
    indent_style: 'tab',
    end_of_line: 'lf'
  })
  .save();
```

**Comment by sapegin** [comment]
https://github.com/sapegin/mrm-tasks/blob/master/packages/mrm-task-editorconfig/Changelog.md#101

**Comment by sapegin** [comment]
Thanks for bug report, fixed in mrm-task-editorconfig. I’ve also updated an example in the readme.
