### ISSUE TITLE
Lines API: add method to insert new line at head of file

### ISSUE THREAD

**Issue by aleung** [sapegin/mrm-core#6]
`lines.add()` appends new line at the end of the file. Sometimes line order matters and need to put a line before others. How about add a new method, or add option to current `add()`, to insert new line(s) at head of file?

**Comment by sapegin** [comment]
Could you share your use case for that? 

`add` doesn’t guarantee any particular order, that’s why it’s `add`, not `append`. For your case we would need to add `prepend` method and rename `add` to `append`, which I don’t really want to do.

Maybe `set` would be more useful, it’ll allow you to do any manipulations with a list and just overwrite an existing value with a new one. It will also be a good match to `get`.

**Comment by aleung** [comment]
A use case is to modify `.gitignore` file as below. To modify/add an exclude line, it must be put a the beginning before include lines.

```
# exclude
*.json

# include
!foo.json
!bar.json
```

I admit that if `prepend` was added then more methods have to be added to make the API complete but looks fragmentary. It can be handled by `get` and `set`.

BTW, `set` is missing in document.

**Comment by sapegin** [comment]
That’s because it’s not implemented yet but may be a good addition to the API ;-)

**Comment by sapegin** [comment]
Released in [2.3.0](https://github.com/sapegin/mrm-core/releases/tag/v2.3.0).
